### ISSUE TITLE
Native promises

### ISSUE THREAD

**Issue by flootr** [peerigon/scrapegoat#13]
Make use of native promises ([mdn - Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)), but stay with when.js to lift functions.
- [ ] use native promises
- [ ] update package.json to require node 0.12
- [ ] update version number (breaking change)

**Comment by meaku** [comment]
You can also add the when.js promise polyfill to stay compatible with node < 0.12

**Comment by flootr** [comment]
Good idea. Thanks.
