### ISSUE TITLE
scrapegoat querying DAViCal?

### ISSUE THREAD

**Issue by rdkgit** [peerigon/scrapegoat#29]
Hi!

Has anyone tested using scrapegoat with the DAViCal calendar server?

When I point a simple node script, using scrapegoat, at my DAViCal server, I get back an empty ctag object when I call getCtag() function at it.

Any suggestions for debugging?

Thanks,

Bobby

**Comment by Maintraxx** [comment]
Some problem here. Simply test > Empty Ctag

**Comment by Maintraxx** [comment]
This is the response:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<multistatus xmlns="DAV:">
        <response>
                <href>/</href>

                    <propstat>
                            <prop>


                                    <displayname>tmp</displayname>


                            </prop>
                        <status>HTTP/1.1 200 OK</status>
                </propstat>

                    <propstat>
                            <prop>


                                            <getctag xmlns="http://calendarserver.org/ns/"/>


                            </prop>
                        <status>HTTP/1.1 404 Not Found</status>
                </propstat>

        </response>
</multistatus>

`

**Comment by acidicX** [comment]
I haven't worked with it before, but you could try to debug by setting breakpoints and checking the logic. Maybe @antosan has some idea where to start

**Comment by Maintraxx** [comment]
I think i found the main problem. You need your personal server address. Here is descriped how to find it:
https://stackoverflow.com/questions/42319487/icloud-calendar-requests

I tried the example from stackoverflow successful. Now, i got the next issue: When I entered my personal server address, i got a 401 response. With curl it works, so i think, there is someting wrong with the request, i will do some debugging now.

**Comment by acidicX** [comment]
If you find a solution we are happy to accept pull requests :)

**Comment by Maintraxx** [comment]
Ok, now it's working. But i guess a general solution is necessarry to make it compatible for other server. 
To use it with an iCloud Account, the following changes are necessarry:

1. Use the correct server address: https://p22-caldav.icloud.com:443/123456789/calendars/
(p22 may be different, and 12345679 is your user id) see: 
https://stackoverflow.com/questions/42319487/icloud-calendar-requests

2. in File **lib/Calendar.js** 
```
        /**
         * Request ctag.
         * With an ctag you can see if anything in the calendar has changed.
         *
         * @returns {Promise}
         */
        getCtag() {
            return request(this.config, "PROPFIND", 0, xml.calendarCtag).then(xmlParser.parseCalendarMultistatus);
        }

```
Change the deep level to 1:
```
        /**
         * Request ctag.
         * With an ctag you can see if anything in the calendar has changed.
         *
         * @returns {Promise}
         */
        getCtag() {
            return request(this.config, "PROPFIND", 1, xml.calendarCtag).then(xmlParser.parseCalendarMultistatus);
        }

```

3. in File **lib/requests.js** 
```
    if (baseConfig.auth) {
        config.auth = {
            sendImmediately: false,
            ...baseConfig.auth
        };
    }

```

Set sendImmediately to true:

```
    if (baseConfig.auth) {
        config.auth = {
            sendImmediately: true,
            ...baseConfig.auth
        };
    }

```

4. in File **lib/xml/parser.js** remove all occurrences of "d:".

**Comment by acidicX** [comment]
I think part one (use the correct server address) is out of scope for scrapegoat. You need to find it and set it before using scrapegoat.

@Maintraxx can you open a pull request with your changes? Then we can have a look at it and see if we can abstract it in a way that works with other servers as well.

**Comment by rdkgit** [comment]
Thanks for the comments.  However, not sure if querying iCloud caldav server is relevant to querying DAViCal servers.  Any idea if the code fixes above will solve the issue with DAViCal?

**Comment by rdkgit** [comment]
Hi!

Just downloaded update and was able to connect to my DaViCAL server and get etags listing a bunch of events.  Thanks!!  I can proceed with my nodejs project.

Bobby
