### ISSUE TITLE
CalDav Tasks?

### ISSUE THREAD

**Issue by MathyEM** [peerigon/scrapegoat#49]
I can't seem to be able to get tasks/todo. I though they would be handled by the same way as events on the caldav server. Is there something I'm missing or would you look into adding the option to get tasks?

If it helps, I am using Nextcloud.

For the record, I am able to get the events from other calendars, just not the from ones that only contain tasks.

Thanks for the package anyways, it's pretty great nonetheless.

**Comment by antosan** [comment]
Thank you @MathyEM for using scrapegoat 🎉 . We built scrapegoat to scrape **events** data from a CalDav server. It was not meant to support getting tasks/todos and there is no plan to add this functionality currently.
